# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Site
title: Questocat's Blog
author: QUESTOCAT

# URL
url: http://questocat.com
root: /
permalink: /blog/:year/:month/:day/:title.html

# RSS
rss: /atom.xml

# Social Links
GitHub: https://github.com/questocat

# Pagination
## Set per_page to 0 to disable pagination
per_page: 1
pagination_dir: page

# ---------------------------------------------------------------
# Analytics settings
# ---------------------------------------------------------------
analytics: google_analytics
# Google Analytics
google_analytics: UA-119958045-1    # Format: UA-xxxxxx-xx

# ---------------------------------------------------------------
# Comment settings
# ---------------------------------------------------------------
comment_provider: disqus
# Disqus settings
disqus_shortname: philzc
