# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# URL
url: http://questocat.com
root: /
SEOTitle: Questocat's Blog
permalink: /blog/:year/:month/:day/:title.html

# Pagination
## Set per_page to 0 to disable pagination
per_page: 1
pagination_dir: page

# ---------------------------------------------------------------
# Analytics settings
# ---------------------------------------------------------------
# Google Analytics
google_analytics: UA-119958045-1    # Format: UA-xxxxxx-xx

# ---------------------------------------------------------------
# Comment settings
# ---------------------------------------------------------------
# Disqus settings
disqus_shortname: philzc

# #rss: /atom.xml

# date_format: YYYY-MM-DD

# copyright_date: 2018
